# we can change the value of variable
cgpa = 12
print(cgpa)
# here you can see that value of variable has beem changed from 12 to 15
cgpa = 15
print(cgpa)
# these are common types of values
student_name = "Ali Don"  #string= text
student_age = 23          #integer=whole numbers
percentage = 4.5          #float=decimal numbers
is_present = True         #boolo=true or false
print(student_name)
print(student_age)
print(percentage)
print(is_present)
# in following code you can see that how user give the input 
# also keep it in your mind that anything we assign for input should be 
# as it is suppose that name in the following code
name = input("ENTER YOUR NAME:")
print("hello" , name)
# INPUT TELLS THE USER WHAT TO ENTER 
profession = input("ENTER YOUR PROFESSION:")
print("I AM STUDENT OF" , profession)
age = input("ENTER YOUR AGE:")
# the vlue of input is normally a string and 
# even if the user enters a number
print("I AM " , age, "years old")
# to perform the claculations convert the input into number
income = input("ENTER YOUR INCOME:")
income1 = input("ENTER YOUR MONTHLY INCOME:")
print("MY DAILY EARNING IS" , income)
print("MY MONTHLY INCOME IS" , income1)
# STORE TONY.S DETAIL IN VARAIBLE
first_name = "TONY"
last_name = "STARK"
age = 45
new_age = int(age+1)
height = 1.45
is_superhero = "TRUE"
# CHECK THE DETAILS OF SUPERHERO
print("---PERSON DETAILS---")
print("FIRST NAME" , first_name)
print("LAST NAME" , last_name)
print("AGE" , age)
print("age after 1 year" , new_age)
print("TONY,S HEIGHT" , height)
print("IS SUPERHERO" , is_superhero)